name: Daily DTC Report

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm' # ช่วยให้โหลดเร็วขึ้น

    - name: Install Dependencies
      # ใช้ npm ci เพื่อความสะอาดและชัวร์กว่า npm install
      run: |
        npm install
        npm list puppeteer # เช็คว่าลงจริงไหม

    - name: Run Script
      run: node index.js
      env:
        DTC_USER: ${{ secrets.DTC_USER }}
        DTC_PASS: ${{ secrets.DTC_PASS }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
