name: Daily DTC Report

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check File Structure
      run: ls -R

    - name: Install Dependencies
      run: npm install

    - name: Run Script
      run: node index.js
      env:
        DTC_USER: ${{ secrets.DTC_USER }}
        DTC_PASS: ${{ secrets.DTC_PASS }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}

    # ส่วนนี้จะช่วยให้คุณเห็นหน้าจอตอน Error ได้
    - name: Upload Debug Screenshots
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: debug-screenshots
        path: downloads/*.png
        retention-days: 5
