name: Daily DTC Report

on:
  schedule:
    - cron: '0 1 * * *' # 8.00 น. เวลาไทย
  workflow_dispatch:      # ปุ่มกดรันมือ

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Check File Structure (Debug)
      run: ls -R  # คำสั่งนี้จะโชว์ว่ามีไฟล์อะไรบ้าง ถ้า package.json หาย เราจะรู้ทันที

    - name: Install Dependencies
      run: npm install

    - name: Run Script
      run: node index.js
      env:
        DTC_USER: ${{ secrets.DTC_USER }}
        DTC_PASS: ${{ secrets.DTC_PASS }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
